transformers:
  - name: chinook_customer_transformer
    schema: Chinook
    table: Customer
    skip_columns: [CustomerId, SupportRepId]
    
    columns:
      FirstName:
        transformer: custom_llm_masker
        prompt_template_file: prompt_templates/name.txt
        field_type: "name"
      
      LastName:
        transformer: custom_llm_masker  
        prompt_template_file: prompt_templates/name.txt
        field_type: "last_name"
      
      Company:
        transformer: static_replace
        replacement: "[COMPANY ANONYMIZED]"
      
      Address:
        transformer: city_preserving_address_masker
        field_type: "street_address"
      
      Phone:
        transformer: mask_phone
        prompt_template_file: prompt_templates/phone.txt
      
      Email:
        transformer: mask_email
  
  - name: chinook_invoice_transformer
    schema: Chinook
    table: Invoice
    skip_columns: [InvoiceId, CustomerId]
    
    columns:
      InvoiceDate:
        transformer: date_shift
        shift_days: -7
      Total:
        transformer: amount_anonymize
